[browser]
gatherUsageStats = false

[server]
enableCORS = false
enableXsrfProtection = false

[theme]
# Light mode settings
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif" 